# Generated by Django 5.1.4 on 2025-02-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id_tratamento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_tratamento', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tratamento',
            },
        ),
    ]
