# Generated by Django 5.1.4 on 2025-02-26 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consulta', '0001_initial'),
        ('tratamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inicio', models.DateField()),
                ('dt_fim', models.DateField()),
                ('diagnostico', models.CharField(max_length=500)),
                ('observacoes', models.CharField(max_length=1000)),
                ('abordagem', models.CharField(max_length=300)),
                ('id_consulta', models.ForeignKey(db_column='id_consulta', on_delete=django.db.models.deletion.DO_NOTHING, to='consulta.consulta')),
                ('id_tratamento', models.ForeignKey(db_column='id_tratamento', on_delete=django.db.models.deletion.DO_NOTHING, to='tratamento.tratamento')),
            ],
        ),
    ]
