# Generated by Django 5.1.4 on 2025-02-26 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
        ('registro_tratamento', '0001_initial'),
        ('tratamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tratamento',
            new_name='RegistroTratamento',
        ),
    ]
