# Generated by Django 5.1.4 on 2025-02-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id_profissional', models.AutoField(primary_key=True, serialize=False)),
                ('telefone', models.CharField(max_length=45)),
                ('num_identificaco', models.CharField(max_length=45)),
                ('sexo', models.CharField(max_length=1)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
